Add `-a` option to some sub-commands
The `ingest`, `accession`, and `dataset` sub-commands gain a `-a`
command line option.  This option is valid when the sub-command is used
for listing the available filenames in a given queue, and makes the
command list the filenames in _all_ buckets.

Note that the output format changes when `-a` is used as the filenames
are prefixed with the bucket thathey reside in.

diff --git a/scripts/sda-admin b/scripts/sda-admin
--- a/scripts/sda-admin
+++ b/scripts/sda-admin
@@ -251,14 +251,14 @@ rotate_dump_files () {
 
 	for i in 8 7 6 5 4 3 2 1 0; do
 		if [ -f "$queue-$i.json" ]; then
-			mv "$queue-$i.json" "$queue-$(( i + 1 )).json"
+			mv -- "$queue-$i.json" "$queue-$(( i + 1 )).json"
 		fi
 	done
 }
 
 get_messages () {
 	# Retrieves the messages from the RabbitMQ queue given by the
-	# 1st argument.  The remaining arguments are pathnames that we
+	# 1st operand.  The remaining operands are pathnames that we
 	# filter the messages with (together with the access key from
 	# the S3 configuration).  Any message that does not correspond
 	# to any of the given pathnames is requeued.  The remaining
@@ -315,23 +315,44 @@ get_messages () {
 
 get_filenames () {
 	# Return the filenames present in the queue given by the 1st
-	# argument.  The messages in the queue are filtered on the
-	# access key from the S3 configuration.
+	# operand.  The messages in the queue are filtered on the access
+	# key from the S3 configuration, unless the "-a" option is
+	# given, in which case all messages are returned.
+
+	OPTIND=1
+	unset -v opt_all
+	while getopts a opt; do
+		case $opt in
+			a)
+				opt_all=true
+				;;
+			*)
+				echo 'Error in command line parsing' >&2
+				exit 1
+		esac
+	done
+	shift "$(( OPTIND - 1 ))"
 
 	queue=$1
 
 	curl --data \
 		'{"count":-1,"encoding":"auto","ackmode":"ack_requeue_true"}' \
 		"$url_queues/$queue/get" |
-	jq -r --arg access_key "$S3_ACCESS_KEY" '
+	jq -r \
+		--argjson no_filter "${opt_all-false}" \
+		--arg access_key "$S3_ACCESS_KEY" '
 		map(
 			.payload |
 			fromjson |
-			select(
-				.filepath |
-				startswith($access_key + "/")
-			).filepath |
-			sub(".*?/"; "")
+			if $no_filter then
+				.filepath
+			else
+				select(
+					.filepath |
+					startswith($access_key + "/")
+				).filepath |
+				sub(".*?/"; "")
+			end
 		) | unique[]'
 }
 
@@ -339,11 +360,25 @@ ingest () {
 	# Ingest the given filenames.  If given a directory path ending
 	# with a slash, ingest all files in or below that path.
 
-	# If no arguments are given, list the filenames that may be
+	OPTIND=1
+	unset -v opt_all
+	while getopts a opt; do
+		case $opt in
+			a)
+				opt_all=true
+				;;
+			*)
+				echo 'Error in command line parsing' >&2
+				exit 1
+		esac
+	done
+	shift "$(( OPTIND - 1 ))"
+
+	# If no operands are given, list the filenames that may be
 	# processed, then return immediately.
 	#
 	if [ "$#" -eq 0 ]; then
-		get_filenames inbox
+		get_filenames ${opt_all+-a} inbox
 		return
 	fi
 
@@ -368,16 +403,30 @@ accession () {
 	# Assign an accession ID to a single ingested file, or assign
 	# multiple accession IDs to several files.
 
-	# If no arguments are given, list the filenames that may be
+	OPTIND=1
+	unset -v opt_all
+	while getopts a opt; do
+		case $opt in
+			a)
+				opt_all=true
+				;;
+			*)
+				echo 'Error in command line parsing' >&2
+				exit 1
+		esac
+	done
+	shift "$(( OPTIND - 1 ))"
+
+	# If no operands are given, list the filenames that may be
 	# processed, then return immediately.
 	#
 	if [ "$#" -eq 0 ]; then
-		get_filenames verified
+		get_filenames ${opt_all+-a} verified
 		return
 	fi
 
-	# We expect either exactly two arguments here (one accession
-	# ID and one filename), or three or more arguments (one
+	# We expect either exactly two operands here (one accession
+	# ID and one filename), or three or more operands (one
 	# format string, an inital counter value, and one or several
 	# pathnames).
 	#
@@ -456,15 +505,29 @@ dataset () {
 	# given with a slash at the end, all files in or beneath that
 	# directory will be assigned to the given dataset ID.
 
-	# If no arguments are given, list the files that may be
+	OPTIND=1
+	unset -v opt_all
+	while getopts a opt; do
+		case $opt in
+			a)
+				opt_all=true
+				;;
+			*)
+				echo 'Error in command line parsing' >&2
+				exit 1
+		esac
+	done
+	shift "$(( OPTIND - 1 ))"
+
+	# If no operands are given, list the files that may be
 	# processed, then return immediately.
 	#
 	if [ "$#" -eq 0 ]; then
-		get_filenames completed
+		get_filenames ${opt_all+-a} completed
 		return
 	fi
 
-	# We expect at least two arguments here; one dataset ID and at
+	# We expect at least two operands here; one dataset ID and at
 	# least one filename.
 	#
 	if [ "$#" -lt 2 ]; then
@@ -509,8 +572,8 @@ restore () {
 	# there are duplicates, the message from the dump file is given
 	# precedence (on account of being seen first).
 
-	# We expect exactly one argument here; the name of the dump
-	# file.  That file must exist.
+	# We expect exactly one operand here; the name of the dump file.
+	# That file must exist.
 	#
 	if [ "$#" -ne 1 ] || [ ! -f "$1" ]; then
 		usage restore >&2
@@ -583,16 +646,16 @@ usage_general () {
 	    $myself help upload
 
 	    $myself [...] ingest pathname [pathname...]
-	    $myself [...] ingest
+	    $myself [...] ingest [-a]
 	    $myself help ingest
 
 	    $myself [...] accession accessionID pathname
 	    $myself [...] accession format start pathname [pathname...]
-	    $myself [...] accession
+	    $myself [...] accession [-a]
 	    $myself help accession
 
 	    $myself [...] dataset datasetID pathname [pathname...]
-	    $myself [...] dataset
+	    $myself [...] dataset [-a]
 	    $myself help dataset
 
 	    $myself [...] restore '<queue>-<n>.json'
@@ -677,6 +740,11 @@ usage_ingest () {
 
 	    $myself ingest
 
+	    The same as the above, but processing all buckets, not just
+	    the one associated with the configured S3 access key:
+
+	    $myself ingest -a
+
 	    Files may be ingested one by one or several at once.
 	    Ingesting three files:
 
@@ -714,6 +782,11 @@ usage_accession () {
 	    waiting to have accession IDs assigned to them:
 
 	    $myself accession
+
+	    The same as the above, but processing all buckets, not just
+	    the one associated with the configured S3 access key:
+
+	    $myself accession -a
 
 	    Accessions are only ever assigned to one file at a time.
 	    Assigning accessions to three files:
@@ -755,6 +828,11 @@ usage_dataset () {
 	    waiting to be associated with a dataset ID:
 
 	    $myself dataset
+
+	    The same as the above, but processing all buckets, not just
+	    the one associated with the configured S3 access key:
+
+	    $myself dataset -a
 
 	    Files are associated to dataset IDs one at a time or several
 	    at once.  Associating three files with a dataset ID:
